import styles from './ScrolldrivenAnimation.module.css'

 function ScrolldrivenAnimation() {

    return (
        <article>
            <h2>ScrolldrivenAnimation</h2>
            <p class={styles.green}>Lorem ipsum dolor sit.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, nobis nulla non cupiditate obcaecati nemo, doloribus suscipit, veritatis recusandae ab saepe ipsam. Eum, temporibus! Ex sequi, repellendus aliquid, quibusdam voluptate porro a veritatis autem eligendi hic eaque sint laudantium dolorem suscipit illum, necessitatibus perspiciatis pariatur quod. Et deleniti accusantium nemo quam alias ullam earum quidem tenetur cumque enim dolore aliquid consequuntur minus, dignissimos eligendi culpa! Debitis illum iure ipsa alias omnis esse tenetur mollitia ipsum consequuntur sapiente perspiciatis, adipisci quae facilis placeat fuga aspernatur doloribus aut dicta veritatis saepe. Similique, voluptatum quaerat architecto aut incidunt dolorem cupiditate recusandae eum rerum quod dolores dolore autem ab! Dolorem at cupiditate velit deserunt commodi incidunt ipsam reiciendis ad ipsum pariatur sequi minima quod, provident ab, optio eos! Itaque quia qui, soluta error rerum deleniti ipsum dolores labore veniam veritatis doloribus culpa ad sunt quam recusandae et dolor similique corporis at iste pariatur quae. Pariatur, libero in iure cumque asperiores deserunt consequuntur voluptatum velit ratione dicta quisquam temporibus illum debitis optio, hic architecto sapiente assumenda fuga, recusandae rerum repudiandae non harum aliquam. Iusto dolorum quo doloremque deserunt reprehenderit, non modi tenetur eligendi sapiente dolore, repellat dignissimos perspiciatis at voluptatem repellendus eum blanditiis officia accusamus.</p>
            <blockquote class={styles.flyIn}>this is flying in, sooooo cooooooool!!!!!!!!</blockquote>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi molestias, eveniet enim sit necessitatibus perferendis minima ullam placeat sequi qui quisquam nobis debitis architecto modi beatae doloribus harum. A sed unde asperiores nostrum similique dolorum inventore iste, hic rerum nobis tempore laudantium sequi dolore architecto aliquam soluta eaque facere non commodi veniam deserunt? Nemo animi enim illo eius perferendis iure reiciendis provident quod nihil adipisci corporis vero inventore, dolores dicta dolor iusto. Neque laudantium ut reprehenderit deserunt officiis, placeat, quasi reiciendis nemo cum odio a. Natus ab voluptatum veniam nam nisi id facilis aut repudiandae quidem eum magnam facere, ipsam praesentium eveniet velit possimus enim, tempore optio eius quae dolorum maxime provident sapiente. Aut, commodi, omnis officia praesentium beatae tempora perspiciatis tenetur laboriosam reprehenderit sunt ex nulla corrupti cumque sequi aliquam ratione mollitia quo! Veritatis aperiam enim ea saepe adipisci, deserunt nobis. Quam, ad nostrum reprehenderit rem itaque dicta eligendi perferendis cupiditate nisi adipisci autem ea provident facilis alias sequi modi delectus iste enim optio? Vero impedit, excepturi distinctio accusamus similique nam consequuntur commodi, et fugit ipsa dolore assumenda cum sit. Enim animi obcaecati explicabo suscipit veniam quod aliquid ab ullam, nam dolorem amet alias quos corporis velit error fugit!</p>

        </article>
    );
}
    export default ScrolldrivenAnimation;